services:
  db:
    image: postgres:alpine
    env_file:
      - .envs/.local/.postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: local.Dockerfile
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .envs/.local/.postgres
      - .envs/.local/.django
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - db
volumes:
  local_postgres_data:
